version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myweatherdb
      - POSTGRES_USER=fahad
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: